// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHtvEcW57NML_Xh6Zb6OiuEgqbuPP8u9s',
    appId: '1:947010097069:web:f149a9313ed14a07329b24',
    messagingSenderId: '947010097069',
    projectId: 'kraiziworld',
    authDomain: 'kraiziworld.firebaseapp.com',
    storageBucket: 'kraiziworld.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Ati0P4Vu0ZWuvjIHH4tyvGqySzhWHWY',
    appId: '1:947010097069:android:8d7b2cb69ea40f9c329b24',
    messagingSenderId: '947010097069',
    projectId: 'kraiziworld',
    storageBucket: 'kraiziworld.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFwrieUrhQyoX9RzlEkkjZqjW3qMKwE04',
    appId: '1:947010097069:ios:d25a7b6886c59cd2329b24',
    messagingSenderId: '947010097069',
    projectId: 'kraiziworld',
    storageBucket: 'kraiziworld.firebasestorage.app',
    iosBundleId: 'com.example.kw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFwrieUrhQyoX9RzlEkkjZqjW3qMKwE04',
    appId: '1:947010097069:ios:d25a7b6886c59cd2329b24',
    messagingSenderId: '947010097069',
    projectId: 'kraiziworld',
    storageBucket: 'kraiziworld.firebasestorage.app',
    iosBundleId: 'com.example.kw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHtvEcW57NML_Xh6Zb6OiuEgqbuPP8u9s',
    appId: '1:947010097069:web:949e6701cbbafd79329b24',
    messagingSenderId: '947010097069',
    projectId: 'kraiziworld',
    authDomain: 'kraiziworld.firebaseapp.com',
    storageBucket: 'kraiziworld.firebasestorage.app',
  );
}
